"""
False Positive (FP) & Whitelist Exception Engine for AegisXDR-Enterprise.
Filters benign noise generated by trusted corporate IT software, browser updaters, and IDE tools
using regex patterns and process hierarchy verification.
"""

import re
import logging
from typing import Dict, Any, List, Tuple, Optional

logger = logging.getLogger("FalsePositiveEngine")

class FalsePositiveEngine:
    """
    Evaluates telemetry events against an exception hierarchy matrix
    to eliminate false positive alert fatigue in SOC operations.
    """
    def __init__(self):
        # Whitelist definitions based on Process Name, Parent Process, Path Regex, and CLI Regex
        self.whitelists: List[Dict[str, Any]] = [
            {
                "name": "Google Chrome Updater Routine",
                "process_regex": r"^googleupdate\.exe$",
                "parent_regex": r"^(services\.exe|svchost\.exe)$",
                "path_regex": r"^c:\\program files (x86)\\google\\update\\googleupdate\.exe$",
                "cmdline_regex": r".*/ua.*"
            },
            {
                "name": "Microsoft Edge Updater Routine",
                "process_regex": r"^microsoftedgeupdate\.exe$",
                "parent_regex": r"^(services\.exe|svchost\.exe)$",
                "path_regex": r"^c:\\program files (x86)\\microsoft\\edgeupdate\\microsoftedgeupdate\.exe$",
                "cmdline_regex": r".*"
            },
            {
                "name": "VS Code Helper Subprocesses",
                "process_regex": r"^code\.exe$",
                "parent_regex": r"^code\.exe$",
                "path_regex": r".*\\appdata\\local\\programs\\microsoft vs code\\code\.exe$",
                "cmdline_regex": r".*--type=(renderer|utility|gpu-process).*"
            },
            {
                "name": "Git for Windows Routine Calls",
                "process_regex": r"^(git\.exe|sh\.exe|bash\.exe)$",
                "parent_regex": r"^(code\.exe|idea64\.exe|cmd\.exe)$",
                "path_regex": r".*\\git\\(cmd|bin|usr\\bin)\\.*",
                "cmdline_regex": r".*git (status|fetch|rev-parse|log|diff).*"
            },
            {
                "name": "Windows System Telemetry Routine",
                "process_regex": r"^compattelrunner\.exe$",
                "parent_regex": r"^taskeng\.exe|svchost\.exe$",
                "path_regex": r"^c:\\windows\\system32\\compattelrunner\.exe$",
                "cmdline_regex": r".*"
            }
        ]

    def is_false_positive(self, event: Dict[str, Any]) -> Tuple[bool, Optional[str]]:
        """
        Evaluates a process telemetry event.
        Returns (True, "Rule Name") if the event matches trusted noise white-lists.
        """
        process_name = (event.get("process_name") or "").lower()
        parent_name = (event.get("parent_name") or event.get("source_name") or "").lower()
        process_path = (event.get("process_path") or event.get("source_path") or "").lower()
        cmdline = (event.get("cmdline") or "").lower()

        for rule in self.whitelists:
            p_match = re.search(rule["process_regex"], process_name, re.IGNORECASE) if rule.get("process_regex") else True
            par_match = re.search(rule["parent_regex"], parent_name, re.IGNORECASE) if rule.get("parent_regex") else True
            path_match = re.search(rule["path_regex"], process_path, re.IGNORECASE) if rule.get("path_regex") else True
            cmd_match = re.search(rule["cmdline_regex"], cmdline, re.IGNORECASE) if rule.get("cmdline_regex") else True

            if p_match and par_match and path_match and cmd_match:
                logger.debug(f"[FP Engine] Whitelisted event ({process_name}) matching rule: {rule['name']}")
                return True, rule["name"]

        return False, None

fp_engine = FalsePositiveEngine()
